In [29]:
import pandas as pd

# Cargar el csv
df = pd.read_csv("files/Valor_Tasado.csv")

In [30]:
df.columns

Index(['Comunidad_Autonoma', 'Año', 'Trimestre', 'Periodo',
       'Valor_Tasado_€_m2'],
      dtype='object')

In [31]:
df_compraventa = pd.read_csv("files/Compraventa.csv", encoding="utf-8", sep=";")

In [32]:
print(df_compraventa.columns)

Index(['Total Nacional', 'Comunidades y Ciudades Autónomas', 'Provincias',
       'Régimen y estado', 'Periodo', 'Total'],
      dtype='object')

In [33]:
df_compraventa["Comunidades y Ciudades Autónomas"].unique()

array([nan, '01 Andalucía', '02 Aragón', '03 Asturias, Principado de',
       '04 Balears, Illes', '05 Canarias', '06 Cantabria',
       '07 Castilla y León', '08 Castilla - La Mancha', '09 Cataluña',
       '10 Comunitat Valenciana', '11 Extremadura', '12 Galicia',
       '13 Madrid, Comunidad de', '14 Murcia, Región de',
       '15 Navarra, Comunidad Foral de', '16 País Vasco', '17 Rioja, La',
       '18 Ceuta', '19 Melilla'], dtype=object)

In [34]:
df_compraventa["Comunidades y Ciudades Autónomas"] = df_compraventa["Comunidades y Ciudades Autónomas"].str.replace(r'^\d+\s', '', regex=True)

df_compraventa["Comunidades y Ciudades Autónomas"].unique()

array([nan, 'Andalucía', 'Aragón', 'Asturias, Principado de',
       'Balears, Illes', 'Canarias', 'Cantabria', 'Castilla y León',
       'Castilla - La Mancha', 'Cataluña', 'Comunitat Valenciana',
       'Extremadura', 'Galicia', 'Madrid, Comunidad de',
       'Murcia, Región de', 'Navarra, Comunidad Foral de', 'País Vasco',
       'Rioja, La', 'Ceuta', 'Melilla'], dtype=object)

In [42]:
# Diccionario de reemplazos: clave = nombre original, valor = nombre normalizado
replacements = {
    'Asturias (Principado de )': 'Asturias, Principado de',
    'Balears (Illes)': 'Balears, Illes',
    'Comunidad Valenciana': 'Comunitat Valenciana',
    'Valencia/València': 'Comunitat Valenciana',
    'Madrid (Comunidad de)': 'Madrid, Comunidad de',
    'Murcia (Región de)': 'Murcia, Región de',
    'Navarra (Com. Foral de)': 'Navarra, Comunidad Foral de',
    'Navarra (Comunidad Foral de)': 'Navarra, Comunidad Foral de',
    'Rioja (La)': 'Rioja, La',
    # Añade más reemplazos si es necesario
}

In [43]:
df['Comunidad_Autonoma'] = df['Comunidad_Autonoma'].replace(replacements)
df["Comunidad_Autonoma"].unique()

array(['Albacete', 'Alicante/Alacant', 'Almería', 'Andalucía',
       'Araba/Alava', 'Aragón', 'Asturias, Principado de', 'Badajoz',
       'Balears, Illes', 'Barcelona', 'Bizkaia', 'Burgos', 'Canarias',
       'Cantabria', 'Castellón/Castelló', 'Castilla y León',
       'Castilla-La Mancha', 'Cataluña', 'Ciudad Real',
       'Comunitat Valenciana', 'Coruña (A)', 'Cuenca', 'Cáceres', 'Cádiz',
       'Córdoba', 'Extremadura', 'Galicia', 'Gipuzkoa', 'Girona',
       'Granada', 'Guadalajara', 'Huelva', 'Huesca', 'Jaén', 'León',
       'Lleida', 'Lugo', 'Madrid, Comunidad de', 'Murcia, Región de',
       'Málaga', 'Navarra, Comunidad Foral de', 'Ourense', 'Palencia',
       'Palmas (Las)', 'País Vasco', 'Pontevedra', 'Rioja, La',
       'Salamanca', 'Santa Cruz de Tenerife', 'Segovia', 'Sevilla',
       'Soria', 'TOTAL NACIONAL', 'Tarragona', 'Teruel', 'Toledo',
       'Valladolid', 'Zamora', 'Zaragoza', 'Ávila', 'Ceuta',
       'Ceuta y Melilla', 'Melilla'], dtype=object)

In [44]:
ccaa = [
   'Andalucía', 
   'Aragón', 
   'Asturias, Principado de',
    'Balears, Illes', 
    'Canarias', 
    'Cantabria', 
    'Castilla y León',
    'Castilla-La Mancha',
    'Cataluña', 
    'Comunitat Valenciana',
    'Extremadura', 
    'Galicia', 
    'Madrid, Comunidad de',
    'Murcia, Región de', 
    'Navarra, Comunidad Foral de', 
    'País Vasco',
    'Rioja, La', 
    'Ceuta', 
    'Melilla']

In [38]:
df_ccaa = df[df["Comunidad_Autonoma"].isin(ccaa)].copy()
df_ccaa.head(10)

         Comunidad_Autonoma   Año  Trimestre Periodo  Valor_Tasado_€_m2
3                 Andalucía  1995          1  1995T1              513.4
5                    Aragón  1995          1  1995T1              573.6
6   Asturias, Principado de  1995          1  1995T1              657.9
8            Balears, Illes  1995          1  1995T1              586.0
12                 Canarias  1995          1  1995T1              572.4
13                Cantabria  1995          1  1995T1              750.0
15          Castilla y León  1995          1  1995T1              616.9
16       Castilla-La Mancha  1995          1  1995T1              505.3
17                 Cataluña  1995          1  1995T1              735.0
19     Comunitat Valenciana  1995          1  1995T1              479.2

In [39]:
df_ccaa["Comunidad_Autonoma"].unique()

array(['Andalucía', 'Aragón', 'Asturias, Principado de', 'Balears, Illes',
       'Canarias', 'Cantabria', 'Castilla y León', 'Castilla-La Mancha',
       'Cataluña', 'Comunitat Valenciana', 'Extremadura', 'Galicia',
       'Madrid, Comunidad de', 'Murcia, Región de',
       'Navarra, Comunidad Foral de', 'País Vasco', 'Rioja, La', 'Ceuta',
       'Melilla'], dtype=object)

In [40]:
df_provincias = df[~df["Comunidad_Autonoma"].isin(ccaa)].copy()
df_provincias.head(10)

    Comunidad_Autonoma   Año  Trimestre Periodo  Valor_Tasado_€_m2
0             Albacete  1995          1  1995T1              438.7
1     Alicante/Alacant  1995          1  1995T1              477.0
2              Almería  1995          1  1995T1              419.8
4          Araba/Alava  1995          1  1995T1              849.0
7              Badajoz  1995          1  1995T1              377.0
9            Barcelona  1995          1  1995T1              860.0
10             Bizkaia  1995          1  1995T1              919.4
11              Burgos  1995          1  1995T1              703.9
14  Castellón/Castelló  1995          1  1995T1              447.8
18         Ciudad Real  1995          1  1995T1              444.2

In [41]:
## Guardar los nuevos csv
df_ccaa.to_csv("valor_m2_ccaa.csv", index=False)
df_provincias.to_csv("valor_m2_provincias.csv", index=False)